default: &default
  adapter: postgresql
  encoding: unicode
  pool: 30

development:
  <<: *default
  database: myapp_development
  username: <%= ENV['username'] %>
  password: <%= ENV['password'] %>

test:
  <<: *default
  database: myapp_test
  username: <%= ENV['username'] %>
  password: <%= ENV['password'] %>

production:
  <<: *default
  database: myapp_production
  username: <%= ENV['username'] %>
  password: <%= ENV['password'] %>


