# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


# Characteristic.create(order: 1, category: "appeal", name: "informative")
# Characteristic.create(order: 2, category: "appeal", name: "practical")
# Characteristic.create(order: 3, category: "appeal", name: "inspiring")
# Characteristic.create(order: 4, category: "appeal", name: "thought provoking")
# Characteristic.create(order: 5, category: "appeal", name: "controversial")
# Characteristic.create(order: 6, category: "appeal", name: "funny")
# Characteristic.create(order: 7, category: "appeal", name: "compasionate")
# Characteristic.create(order: 8, category: "appeal", name: "encouraging")
# Characteristic.create(order: 9, category: "appeal", name: "touching")

# Characteristic.create(order: 1, category: "writing category", name: "Upcoming/Recent Events")
# Characteristic.create(order: 2, category: "writing category", name: "Product Reviews")
# Characteristic.create(order: 3, category: "writing category", name: "Tips & Tricks")
# Characteristic.create(order: 4, category: "writing category", name: "Top 10 Lists")
# Characteristic.create(order: 5, category: "writing category", name: "Helpful Tools/Apps")
# Characteristic.create(order: 6, category: "writing category", name: "How To’s")
# Characteristic.create(order: 7, category: "writing category", name: "Hot Industry Topics")
# Characteristic.create(order: 8, category: "writing category", name: "Answer Common FAQs")
# Characteristic.create(order: 9, category: "writing category", name: "Client Testimonials")
# Characteristic.create(order: 10, category: "writing category", name: "Case Studies")
# Characteristic.create(order: 11, category: "writing category", name: "Poll Results")
# Characteristic.create(order: 12, category: "writing category", name: "Video Posts")
# Characteristic.create(order: 13, category: "writing category", name: "Funny Stories")
# Characteristic.create(order: 14, category: "writing category", name: "Personal Stories")
# Characteristic.create(order: 15, category: "writing category", name: "Book Reviews")
# Characteristic.create(order: 16, category: "writing category", name: "Interviews")
# Characteristic.create(order: 17, category: "writing category", name: "First Hand Experiences")
# Characteristic.create(order: 18, category: "writing category", name: "Social Event Commentary")

# Characteristic.create(order: 1, category: "call to action", name: "Recipes")
# Characteristic.create(order: 2, category: "call to action", name: "RD Session")
# Characteristic.create(order: 3, category: "call to action", name: "Products")
# Characteristic.create(order: 4, category: "call to action", name: "Articles")
# Characteristic.create(order: 5, category: "call to action", name: "Community Discussion")


# Characteristic.create(order: 1, category: "diagnosis stage", name: "Asymptomatic")
# Characteristic.create(order: 2, category: "diagnosis stage", name: "Symptomatic")
# Characteristic.create(order: 3, category: "diagnosis stage", name: "Pre Diagnosis")
# Characteristic.create(order: 4, category: "diagnosis stage", name: "During Diagnosis")
# Characteristic.create(order: 5, category: "diagnosis stage", name: "Post Diagnosis")
# Characteristic.create(order: 6, category: "diagnosis stage", name: "< 1 Year After Diagnosis")
# Characteristic.create(order: 8, category: "diagnosis stage", name: "Early in Life Onset")
# Characteristic.create(order: 9, category: "diagnosis stage", name: "Late in Life Onset")
# Characteristic.create(order: 7, category: "diagnosis stage", name: "Experienced")
# Characteristic.create(order: 10, category: "diagnosis stage", name: "Continuous Diagnosis")
# Characteristic.create(category: "Cook Time", name: "Under 20 minutes")
# Characteristic.create(category: "Cook Time", name: "30 minutes")
# Characteristic.create(category: "Cook Time", name: "1 hour")
# Characteristic.create(category: "Cook Time", name: "1.5 hours")
# Characteristic.create(category: "Cook Time", name: "2 hours")
# Characteristic.create(category: "Cook Time", name: "2.5 hours")
# Characteristic.create(category: "Cook Time", name: "3 hours")
# Characteristic.create(category: "Cook Time", name: "3.5 hours")
# Characteristic.create(category: "Cook Time", name: "4 hours")
# Characteristic.create(category: "Cook Time", name: "4.5 hours")
# Characteristic.create(category: "Cook Time", name: "5 hours")
# Characteristic.create(category: "Cook Time", name: "5.5 hours")
# Characteristic.create(category: "Cook Time", name: "6-9 hours")
# Characteristic.create(category: "Cook Time", name: "9-12 hours")
# Characteristic.create(category: "Cook Time", name: "12-24 hours")
# Characteristic.create(category: "Cook Time", name: "2 days")

# Characteristic.create(category: "Prep Time", name: "Under 30 minutess")
# Characteristic.create(category: "Prep Time", name: "30 minutes")
# Characteristic.create(category: "Prep Time", name: "1 hour")
# Characteristic.create(category: "Prep Time", name: "1.5 hours")
# Characteristic.create(category: "Prep Time", name: "2 hours")
# Characteristic.create(category: "Prep Time", name: "2.5 hours")
# Characteristic.create(category: "Prep Time", name: "3 hours")
# Characteristic.create(category: "Prep Time", name: "3.5 hours")
# Characteristic.create(category: "Prep Time", name: "4 hours")
# Characteristic.create(category: "Prep Time", name: "4.5 hours")
# Characteristic.create(category: "Prep Time", name: "5 hours")
# Characteristic.create(category: "Prep Time", name: "5.5 hours")
# Characteristic.create(category: "Prep Time", name: "6-9 hours")
# Characteristic.create(category: "Prep Time", name: "9+ hours")

# Characteristic.create(category: "Difficulty", name: "Simple")
# Characteristic.create(category: "Difficulty", name: "Easy")
# Characteristic.create(category: "Difficulty", name: "Standard")
# Characteristic.create(category: "Difficulty", name: "Expert")

# Characteristic.create(category: "Course", name: "Breakfast")
# Characteristic.create(category: "Course", name: "Lunch")
# Characteristic.create(category: "Course", name: "Dinner")
# Characteristic.create(category: "Course", name: "Snack")
# Characteristic.create(category: "Course", name: "Dessert")
# Characteristic.create(category: "Course", name: "Beverage")
# Characteristic.create(category: "Course", name: "Salad")
# Characteristic.create(category: "Course", name: "Soup")
# Characteristic.create(category: "Course", name: "Appetizer")
# Characteristic.create(category: "Course", name: "Condiments, Dips, & Sauces")
# Characteristic.create(category: "Course", name: "Cocktails")

# Characteristic.create(category: "Age Group", name: "Infant")
# Characteristic.create(category: "Age Group", name: "Breastfeeding")
# Characteristic.create(category: "Age Group", name: "Transition Foods")
# Characteristic.create(category: "Age Group", name: "Toddler")
# Characteristic.create(category: "Age Group", name: "Pre-School")
# Characteristic.create(category: "Age Group", name: "School Age")
# Characteristic.create(category: "Age Group", name: "Adolescent")
# Characteristic.create(category: "Age Group", name: "College")
# Characteristic.create(category: "Age Group", name: "Adult")

# Characteristic.create(category: "Scenario", name: "On The Go")
# Characteristic.create(category: "Scenario", name: "Cook Out")
# Characteristic.create(category: "Scenario", name: "Birthday Party")
# Characteristic.create(category: "Scenario", name: "School Lunch")
# Characteristic.create(category: "Scenario", name: "Picky Eater")
# Characteristic.create(category: "Scenario", name: "Multiple Meals")
# Characteristic.create(category: "Scenario", name: "Last Minute Meals")
# Characteristic.create(category: "Scenario", name: "Dinner Guests")
# Characteristic.create(category: "Scenario", name: "Baby Sitter")
# Characteristic.create(category: "Scenario", name: "Block Party")
# Characteristic.create(category: "Scenario", name: "Prepare In Advance")
# Characteristic.create(category: "Scenario", name: "Game Day")

# Characteristic.create(category: "Holiday", name: "Christmas")
# Characteristic.create(category: "Holiday", name: "Halloween")
# Characteristic.create(category: "Holiday", name: "Thanksgiving")
# Characteristic.create(category: "Holiday", name: "Valentine's Day")
# Characteristic.create(category: "Holiday", name: "Hannukah")
# Characteristic.create(category: "Holiday", name: "New Year's Eve")
# Characteristic.create(category: "Holiday", name: "Easter")
# Characteristic.create(category: "Holiday", name: "Memorial Day")
# Characteristic.create(category: "Holiday", name: "Independence Day")
# Characteristic.create(category: "Holiday", name: "Labor Day")
# Characteristic.create(category: "Holiday", name: "Cinco De Mayo")
# Characteristic.create(category: "Holiday", name: "Day of the Dead")
# Characteristic.create(category: "Holiday", name: "Rosh Hashanah")
# Characteristic.create(category: "Holiday", name: "Yom Kippur")
# Characteristic.create(category: "Holiday", name: "Ramadan")

# Characteristic.create(category: "Culture", name: "American")
# Characteristic.create(category: "Culture", name: "Chinese")
# Characteristic.create(category: "Culture", name: "Italian")
# Characteristic.create(category: "Culture", name: "Middle Eastern")
# Characteristic.create(category: "Culture", name: "Indian")
# Characteristic.create(category: "Culture", name: "Jewish")
# Characteristic.create(category: "Culture", name: "Japanese")
# Characteristic.create(category: "Culture", name: "Taiwanese")
# Characteristic.create(category: "Culture", name: "Italian American")
# Characteristic.create(category: "Culture", name: "Mexican")
# Characteristic.create(category: "Culture", name: "Barbecue")
# Characteristic.create(category: "Culture", name: "Southwestern")
# Characteristic.create(category: "Culture", name: "Southern")
# Characteristic.create(category: "Culture", name: "Soul Food")
# Characteristic.create(category: "Culture", name: "Barbecue")
# Characteristic.create(category: "Culture", name: "Cajun")
# Characteristic.create(category: "Culture", name: "French")
# Characteristic.create(category: "Culture", name: "Greek")
# Characteristic.create(category: "Culture", name: "Hawaiian")
# Characteristic.create(category: "Culture", name: "Irish")
# Characteristic.create(category: "Culture", name: "Cuban")
# Characteristic.create(category: "Culture", name: "English")
# Characteristic.create(category: "Culture", name: "Portuguese")

Characteristic.create(category: "Serving Size", name: "1 person")
Characteristic.create(category: "Serving Size", name: "2 people")
Characteristic.create(category: "Serving Size", name: "3 people")
Characteristic.create(category: "Serving Size", name: "4 people")
Characteristic.create(category: "Serving Size", name: "5 people")
Characteristic.create(category: "Serving Size", name: "6 people")
Characteristic.create(category: "Serving Size", name: "7 people")
Characteristic.create(category: "Serving Size", name: "8 people")
Characteristic.create(category: "Serving Size", name: "9 people")
Characteristic.create(category: "Serving Size", name: "10 or more people")
# # 
# #


# PatientGroup.create(name: "Wheat", category: "allergy", order: 9).allergens << Allergen.create(name: "wheat", description: "The grain of the wheat plant.")
# PatientGroup.create(name: "Peanut", category: "allergy", order: 5).allergens << Allergen.create(name: "peanut")
# PatientGroup.create(name: "Dairy", category: "allergy", order: 4).allergens << Allergen.create(name: "dairy", description: "Containing or made from milk.")
# PatientGroup.create(name: "Tree Nut", category: "allergy", order: 8).allergens << Allergen.create(name: "walnut") << Allergen.create(name: "tree nut")
# PatientGroup.create(name: "Shellfish", category: "allergy", order: 7).allergens << Allergen.create(name: "shellfish")
# PatientGroup.create(name: "Fish", category: "allergy", order: 3).allergens << Allergen.create(name: "fish")
# PatientGroup.create(name: "Egg", category: "allergy", order: 2).allergens << Allergen.create(name: "egg")
# PatientGroup.create(name: "Soy", category: "allergy", order: 8).allergens << Allergen.create(name: "soy")
# PatientGroup.create(name: "Corn", category: "allergy", order: 1).allergens << Allergen.create(name: "corn")
# PatientGroup.create(name: "Sesame", category: "allergy", order: 6).allergens << Allergen.create(name: "sesame")
# PatientGroup.create(name: "Sulfites", category: "allergy", order: 8).allergens << Allergen.create(name: "sulfites")
# PatientGroup.create(name: "Sunflower Seed", category: "allergy", order: 1).allergens << Allergen.create(name: "sunflower seed")
# PatientGroup.create(name: "Sesame", category: "allergy", order: 6).allergens << Allergen.create(name: "sesame")
# PatientGroup.create(name: "Celery Seed", category: "allergy", order: 6).allergens << Allergen.create(name: "celery seed")
# PatientGroup.create(name: "Other Allergy", category: "allergy", order: 10, input_option: true, description: "If an allergy affecting your family's diet isn't listed, please add it below! (Example: Chicken, Strawberry)")

# PatientGroup.create(name: "Gluten Intolerance (non-celiac)", category: "intolerance", order: 101, description: "").allergens << Allergen.create(name: "gluten", description: "A substance present in cereal grains, wheat, barley, rye and oats, that is responsible for the elastic texture of dough")

# PatientGroup.create(name: "Lactose Intolerance", category: "intolerance", order: 102).allergens << Allergen.create(name: "lactose", description: "A sugar present in milk. It is a disaccharide containing glucose and galactose units.")

# PatientGroup.create(name: "Other Intolerance", category: "intolerance", order: 103, input_option: true, description: "If an intolerance affecting your family's diet isn't listed, please add it below! ")


# PatientGroup.create(name: "Celiac Disease", category: "disease", order: 202).allergens << Allergen.where(name: "gluten").first 

# PatientGroup.create(name: "Allergic Colitis", category: "disease", order: 201).allergens << Allergen.where(name: "dairy").first

# PatientGroup.create(name: "Oral Allergy Syndrome", category: "disease", order: 208)

# PatientGroup.create(name: "EoE", category: "disease", order: 205, description: "Eosinophilic Esophogitis")
# PatientGroup.create(name: "CSID", category: "disease", order: 204, description: "Congenital Sucrase-Isomaltase Deficiency")
# PatientGroup.create(name: "FPIES", category: "disease", order: 206, description: "Food Protein Induced Enterocolitis Syndrome")
# PatientGroup.create(name: "IBS", category: "disease", order: 207, description: "Irritable Bowel Syndrome")
# PatientGroup.create(name: "Diabetes", category: "disease", order: 207, description: "Irritable Bowel Syndrome")
# PatientGroup.create(name: "Crohn's Disease", category: "disease", order: 203)
# PatientGroup.create(name: "Other Disease", input_option: true, category: "disease", order: 209, description: "If a disease affecting your family's diet isn't listed, please add it below!")
# PatientGroup.create(name: "Not Sure Yet", category: "none", order: 301)
