# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Characteristic.create(category: "Cook Time", name: "Under 20 minutes")
# Characteristic.create(category: "Cook Time", name: "30 minutes")
# Characteristic.create(category: "Cook Time", name: "1 hour")
# Characteristic.create(category: "Cook Time", name: "1.5 hours")
# Characteristic.create(category: "Cook Time", name: "2 hours")
# Characteristic.create(category: "Cook Time", name: "2.5 hours")
# Characteristic.create(category: "Cook Time", name: "3 hours")
# Characteristic.create(category: "Cook Time", name: "3.5 hours")
# Characteristic.create(category: "Cook Time", name: "4 hours")
# Characteristic.create(category: "Cook Time", name: "4.5 hours")
# Characteristic.create(category: "Cook Time", name: "5 hours")
# Characteristic.create(category: "Cook Time", name: "5.5 hours")
# Characteristic.create(category: "Cook Time", name: "6-9 hours")
# Characteristic.create(category: "Cook Time", name: "9-12 hours")
# Characteristic.create(category: "Cook Time", name: "12-24 hours")
# Characteristic.create(category: "Cook Time", name: "2 days")

# Characteristic.create(category: "Prep Time", name: "Under 20 minutess")
# Characteristic.create(category: "Prep Time", name: "30 minutes")
# Characteristic.create(category: "Prep Time", name: "1 hour")
# Characteristic.create(category: "Prep Time", name: "1.5 hours")
# Characteristic.create(category: "Prep Time", name: "2 hours")
# Characteristic.create(category: "Prep Time", name: "2.5 hours")
# Characteristic.create(category: "Prep Time", name: "3 hours")
# Characteristic.create(category: "Prep Time", name: "3.5 hours")
# Characteristic.create(category: "Prep Time", name: "4 hours")
# Characteristic.create(category: "Prep Time", name: "4.5 hours")
# Characteristic.create(category: "Prep Time", name: "5 hours")
# Characteristic.create(category: "Prep Time", name: "5.5 hours")
# Characteristic.create(category: "Prep Time", name: "6-9 hours")
# Characteristic.create(category: "Prep Time", name: "9-12 hours")
# Characteristic.create(category: "Prep Time", name: "12-24 hours")
# Characteristic.create(category: "Prep Time", name: "2 days")

# Characteristic.create(category: "Difficulty", name: "Simple")
# Characteristic.create(category: "Difficulty", name: "Easy")
# Characteristic.create(category: "Difficulty", name: "Standard")
# Characteristic.create(category: "Difficulty", name: "Expert")

# Characteristic.create(category: "Course", name: "Breakfast")
# Characteristic.create(category: "Course", name: "Lunch")
# Characteristic.create(category: "Course", name: "Dinner")
# Characteristic.create(category: "Course", name: "Snack")
# Characteristic.create(category: "Course", name: "Dessert")

# Characteristic.create(category: "Age Group", name: "Infant")
# Characteristic.create(category: "Age Group", name: "Toddler")
# Characteristic.create(category: "Age Group", name: "Pre-School")
# Characteristic.create(category: "Age Group", name: "School Age")
# Characteristic.create(category: "Age Group", name: "Adolescent")
# Characteristic.create(category: "Age Group", name: "College")
# Characteristic.create(category: "Age Group", name: "Adult")

# Characteristic.create(category: "Scenario", name: "On The Go")
# Characteristic.create(category: "Scenario", name: "Cook Out")
# Characteristic.create(category: "Scenario", name: "Birthday Party")
# Characteristic.create(category: "Scenario", name: "School Lunch")

# Characteristic.create(category: "Holiday", name: "Christmas")
# Characteristic.create(category: "Holiday", name: "Halloween")
# Characteristic.create(category: "Holiday", name: "Thanksgiving")
# Characteristic.create(category: "Holiday", name: "Valentine's Day")
# Characteristic.create(category: "Holiday", name: "Hannukah")

# Characteristic.create(category: "Culture", name: "American")
# Characteristic.create(category: "Culture", name: "Chinese")
# Characteristic.create(category: "Culture", name: "Italian")
# Characteristic.create(category: "Culture", name: "Middle Eastern")
# Characteristic.create(category: "Culture", name: "Indian")

Ingredient.create(name: "Apple", category: "Fruit")
Ingredient.create(name: "Banana", category: "Fruit")
