require "administrate/base_dashboard"

class UserDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    roles: Field::HasMany.with_options(class_name: "UserRole"),
    invited_by: Field::Polymorphic,
    invitations: Field::HasMany.with_options(class_name: "User"),
    user_families: Field::HasMany,
    families: Field::HasMany,
    head_of_families: Field::HasMany.with_options(class_name: "Family"),
    monologue_user: Field::BelongsTo.with_options(class_name: "Monologue::User"),
    patient_groups: Field::HasMany,
    coupon_redemptions: Field::HasMany,
    coupons: Field::HasMany,
    user_packages: Field::HasMany,
    packages: Field::HasMany,
    appointments: Field::HasMany,
    patient_focus: Field::HasMany.with_options(class_name: "Appointment"),
    appointment_hosts: Field::HasMany.with_options(class_name: "Appointment"),
    rooms: Field::HasMany,
    subscriptions: Field::HasMany,
    member_plans: Field::HasMany,
    growth_chart: Field::HasOne,
    food_diary: Field::HasOne,
    post_recommendations: Field::HasMany,
    images: Field::HasMany,
    surveys: Field::HasMany,
    id: Field::Number,
    email: Field::String,
    encrypted_password: Field::String,
    reset_password_token: Field::String,
    reset_password_sent_at: Field::DateTime,
    remember_created_at: Field::DateTime,
    sign_in_count: Field::Number,
    current_sign_in_at: Field::DateTime,
    last_sign_in_at: Field::DateTime,
    current_sign_in_ip: Field::String,
    last_sign_in_ip: Field::String,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
    first_name: Field::String,
    last_name: Field::String,
    phone_number: Field::String,
    date_of_birth: Field::DateTime,
    sex: Field::String,
    height_inches: Field::Number,
    weight_ounces: Field::Number,
    stripe_id: Field::Text,
    family_note: Field::Text,
    family_role: Field::String,
    early_access: Field::Boolean,
    tara_referral: Field::Boolean,
    zip_code: Field::String,
    qol_referral: Field::Boolean,
    confirmation_token: Field::String,
    confirmed_at: Field::DateTime,
    confirmation_sent_at: Field::DateTime,
    due_date: Field::DateTime,
    registration_stage: Field::Number,
    invitation_token: Field::String,
    invitation_created_at: Field::DateTime,
    invitation_sent_at: Field::DateTime,
    invitation_accepted_at: Field::DateTime,
    invitation_limit: Field::Number,
    invitations_count: Field::Number,
    time_zone: Field::String,
    physician_referral: Field::Boolean,
    provider: Field::Boolean,
    hospitals_or_practices: Field::Text,
    academic_affiliations: Field::Text,
    specialty: Field::String,
    subspecialty: Field::String,
    fax: Field::String,
    terms_accepted: Field::Boolean,
    monologue_user_id: Field::Number,
  }.freeze

  # COLLECTION_ATTRIBUTES
  # an array of attributes that will be displayed on the model's index page.
  #
  # By default, it's limited to four items to reduce clutter on index pages.
  # Feel free to add, remove, or rearrange items.
  COLLECTION_ATTRIBUTES = [
    :id,
    :first_name,
    :last_name,
    :email,
    :phone_number,
    :zip_code,
    :time_zone
  ].freeze

  # SHOW_PAGE_ATTRIBUTES
  # an array of attributes that will be displayed on the model's show page.
  SHOW_PAGE_ATTRIBUTES = [
    :roles,
    :invited_by,
    :invitations,
    :user_families,
    :families,
    :head_of_families,
    :monologue_user,
    :patient_groups,
    :coupon_redemptions,
    :coupons,
    :user_packages,
    :packages,
    :appointments,
    :patient_focus,
    :appointment_hosts,
    :rooms,
    :subscriptions,
    :member_plans,
    :growth_chart,
    :food_diary,
    :post_recommendations,
    :images,
    :surveys,
    :id,
    :email,
    :encrypted_password,
    :reset_password_token,
    :reset_password_sent_at,
    :remember_created_at,
    :sign_in_count,
    :current_sign_in_at,
    :last_sign_in_at,
    :current_sign_in_ip,
    :last_sign_in_ip,
    :created_at,
    :updated_at,
    :first_name,
    :last_name,
    :phone_number,
    :date_of_birth,
    :sex,
    :height_inches,
    :weight_ounces,
    :stripe_id,
    :family_note,
    :family_role,
    :early_access,
    :tara_referral,
    :zip_code,
    :qol_referral,
    :confirmation_token,
    :confirmed_at,
    :confirmation_sent_at,
    :due_date,
    :registration_stage,
    :invitation_token,
    :invitation_created_at,
    :invitation_sent_at,
    :invitation_accepted_at,
    :invitation_limit,
    :invitations_count,
    :time_zone,
    :physician_referral,
    :provider,
    :hospitals_or_practices,
    :academic_affiliations,
    :specialty,
    :subspecialty,
    :fax,
    :terms_accepted,
    :monologue_user_id,
  ].freeze

  # FORM_ATTRIBUTES
  # an array of attributes that will be displayed
  # on the model's form (`new` and `edit`) pages.
  FORM_ATTRIBUTES = [
    :roles,
    :invited_by,
    :invitations,
    :user_families,
    :families,
    :head_of_families,
    :monologue_user,
    :patient_groups,
    :coupon_redemptions,
    :coupons,
    :user_packages,
    :packages,
    :appointments,
    :patient_focus,
    :appointment_hosts,
    :rooms,
    :subscriptions,
    :member_plans,
    :growth_chart,
    :food_diary,
    :post_recommendations,
    :images,
    :surveys,
    :email,
    :encrypted_password,
    :reset_password_token,
    :reset_password_sent_at,
    :remember_created_at,
    :sign_in_count,
    :current_sign_in_at,
    :last_sign_in_at,
    :current_sign_in_ip,
    :last_sign_in_ip,
    :first_name,
    :last_name,
    :phone_number,
    :date_of_birth,
    :sex,
    :height_inches,
    :weight_ounces,
    :stripe_id,
    :family_note,
    :family_role,
    :early_access,
    :tara_referral,
    :zip_code,
    :qol_referral,
    :confirmation_token,
    :confirmed_at,
    :confirmation_sent_at,
    :due_date,
    :registration_stage,
    :invitation_token,
    :invitation_created_at,
    :invitation_sent_at,
    :invitation_accepted_at,
    :invitation_limit,
    :invitations_count,
    :time_zone,
    :physician_referral,
    :provider,
    :hospitals_or_practices,
    :academic_affiliations,
    :specialty,
    :subspecialty,
    :fax,
    :terms_accepted,
    :monologue_user_id,
  ].freeze

  # Overwrite this method to customize how users are displayed
  # across all pages of the admin dashboard.
  #
  # def display_resource(user)
  #   "User ##{user.id}"
  # end
end
